services:

  # Frontend service
  smart_team_client_side:
    container_name: smart_team_frontend
    build:
      context: ./clientSide
    volumes:
      - ./clientSide/:/app
    ports:
      - "3000:3000"

  # Backend service
  smart_team_server_side:
    container_name: smart_team_backend
    build:
      context: ./serverSide
    ports:
      - "3001:3000"

  # Mariadb database
  smart_team_database:
    container_name: smart_team_database
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: smart_team_database
      MYSQL_USER: smart_team
      MYSQL_PASSWORD: smart_team
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
    driver: local
