version: '3'
services:
  # Frontend service using Next.js
  frontend:
    build:
      context: ./clientSide
    ports:
      - "3000"
#    depends_on:
#      - backend
#    environment:
#      - BACKEND_URL=http://backend:8080
    networks:
      - app-network
    image: node

  # Backend service using PHP
#  backend:
#    build:
#      context: ./serverSide
#    ports:
#      - "8080:80"
#    depends_on:
#      - database
#    networks:
#      - app-network
#
#  # MariaDB database service
#  database:
#    image: mariadb:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: examplepassword
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: mypassword
#    volumes:
#      - db-data:/var/lib/mysql
#    networks:
#      - app-network
#
#volumes:
#  db-data:

networks:
  app-network: