version: '1.0'
services:

  # Frontend service
  smart_team_client_side:
    container_name: smart_team_frontend
    build:
      context: ./clientSide
    volumes:
      - ./clientSide/:/app
    ports:
      - "3000:3000"

  # Backend service
  smart_team_server_side:
    container_name: smart_team_backend
    build:
      context: ./serverSide
    ports:
      - "3001:3000"

  # Postgres database
  smart_team_database:
    container_name: smart_team_database
    image: postgres:latest
    environment:
      POSTGRES_USER: team
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smart_team_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
