version: '3'
services:
#   Frontend service using Next.js
  frontend:
    image: node:20
    build:
      context: ./clientSide
    ports:
      - "3000:3000"
#    depends_on:
#      - backend
#    environment:
#      - BACKEND_URL=http://backend:8080
    networks:
      smart_team:


  # mysql database service
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: smart_team_database
      MYSQL_USER: smart_team
      MYSQL_PASSWORD: smart_team
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
    driver: local

networks:
  smart_team: