version: '3.8'
services:

  clientside:
    container_name: clientside
    build:
      context: client_side
    labels:
      - traefik.enable=true
      - traefik.http.routers.client_side.rule=Host(`client.dev.local`)
      - traefik.http.services.client_side.loadbalancer.server.port=3000
    volumes:
      - ./client_side/:/app
    networks:
      - smart_team_network

  serverside:
    container_name: serverside
    build:
      context: ./server_side
    labels:
      - traefik.enable=true
      - traefik.http.routers.server_side.rule=Host(`server.dev.local`)
      - traefik.http.services.server_side.loadbalancer.server.port=3000
    volumes:
      - ./server_side/:/app
    networks:
      - smart_team_network

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: team
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: smart_team_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart_team_network

  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - smart_team_network

volumes:
  postgres_data:

networks:
  smart_team_network:
    driver: bridge
