version: '3'
services:
#   Frontend service using Next.js
  frontend:
    build:
      context: ./clientSide
    volumes:
      - ./clientSide/:/app
    ports:
      - "3000:3000"

  # mysql database service
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: smart_team_database
      MYSQL_USER: smart_team
      MYSQL_PASSWORD: smart_team
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  authentication:
    build:
      context: ./serverSide/Authentication
    ports:
      - "3001:3000"

  user_service:
    build:
      context: ./serverSide/UserService
    volumes:
      - ./clientSide/:/app
    ports:
      - "3002:3000"

  company_service:
    build:
      context: ./serverSide/CompanyService
    volumes:
      - ./clientSide/:/app
    ports:
      - "3003:3000"

  notification_service:
    build:
      context: ./serverSide/NotificationService
    volumes:
      - ./clientSide/:/app
    ports:
      - "3003:3000"

volumes:
  mysql_data:
    driver: local
