import type { Metadata } from 'next';
import LayoutHeader from "@/app/components/LayoutHeader/LayoutHeader";
import NavigationMenu from "@/app/components/NavigationMenu/NavigationMenu";
import React from 'react';

export const metadata: Metadata = {
    title: 'SmartTeam',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
    children: React.ReactNode
}) {
    return (
        <>
            <LayoutHeader />
            <NavigationMenu />
            {children}
        </>
    )
}
