import type { Metadata } from 'next';
import LayoutHeader from '@/app/components/layoutComponents/LayoutHeader/LayoutHeader';
import NavigationMenu from '@/app/components/layoutComponents/NavigationMenu/NavigationMenu';
import React from 'react';

export const metadata: Metadata = {
    title: 'SmartTeam',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: {
    children: React.ReactNode
}) {
    return (
        <>
            <LayoutHeader firstName={'David'}
                          lastName={'Voskanyan'}
                          avatarColor={'#2e2e2e'}
                          imageFileName={''}
            />
            <NavigationMenu />
            {children}
        </>
    );
}
